// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/question/add": {
            "post": {
                "description": "添加问题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "添加问题",
                "parameters": [
                    {
                        "description": "question",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.QuestionAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/question/get/{id}": {
            "get": {
                "description": "根据id获取题目",
                "produces": [
                    "application/json"
                ],
                "summary": "根据id获取题目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/test/{id}": {
            "get": {
                "description": "描述信息",
                "produces": [
                    "application/json"
                ],
                "summary": "测试接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/user/getLoginUser": {
            "get": {
                "description": "获取登录用户",
                "produces": [
                    "application/json"
                ],
                "summary": "获取登录用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "pb.JudgeCase": {
            "type": "object",
            "properties": {
                "inputs": {
                    "description": "用例输入",
                    "type": "string"
                },
                "outputs": {
                    "description": "用例输出",
                    "type": "string"
                }
            }
        },
        "pb.JudgeConfig": {
            "type": "object",
            "properties": {
                "memoryLimit": {
                    "description": "内存限制",
                    "type": "integer"
                },
                "stackLimit": {
                    "description": "堆栈限制",
                    "type": "integer"
                },
                "timeLimit": {
                    "description": "时间限制",
                    "type": "integer"
                }
            }
        },
        "pb.QuestionAddRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "judgeCase": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.JudgeCase"
                    }
                },
                "judgeConfig": {
                    "$ref": "#/definitions/pb.JudgeConfig"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "pb.UserLoginRequest": {
            "type": "object",
            "properties": {
                "userName": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "userPassword": {
                    "description": "密码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "swaggo测试",
	Description:      "swaggo测试API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
