definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  pb.JudgeCase:
    properties:
      inputs:
        description: 用例输入
        type: string
      outputs:
        description: 用例输出
        type: string
    type: object
  pb.JudgeConfig:
    properties:
      memoryLimit:
        description: 内存限制
        type: integer
      stackLimit:
        description: 堆栈限制
        type: integer
      timeLimit:
        description: 时间限制
        type: integer
    type: object
  pb.QuestionAddRequest:
    properties:
      answer:
        type: string
      context:
        type: string
      judgeCase:
        items:
          $ref: '#/definitions/pb.JudgeCase'
        type: array
      judgeConfig:
        $ref: '#/definitions/pb.JudgeConfig'
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  pb.UserLoginRequest:
    properties:
      userName:
        description: 用户昵称
        type: string
      userPassword:
        description: 密码
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: swaggo测试API文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: swaggo测试
  version: "1.0"
paths:
  /question/add:
    post:
      consumes:
      - application/json
      description: 添加问题
      parameters:
      - description: question
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/pb.QuestionAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 添加问题
  /question/get/{id}:
    get:
      description: 根据id获取题目
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 根据id获取题目
  /test/{id}:
    get:
      description: 描述信息
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 测试接口
  /user/getLoginUser:
    get:
      description: 获取登录用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 获取登录用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/pb.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 用户登录
swagger: "2.0"
