svr_config:
  name: "judgesvr"
  host: "127.0.0.1"
  port: "8005"
  user_svr_name : "usersvr"
  question_svr_name : "questionsvr"
  questionsubmit_svr_name: "questionsubmitsvr"
  codesand_svr_name: "codesandsvr"



redis:
  host: "127.0.0.1"
  password: "123456"
  db: 0
  port: 6379
  PoolSize: 10

mysql:
  host: "127.0.0.1"
  port: 3306
  database: oj
  username: root
  password: 123456

log:
  level: "debug"
  file_name: "codesand.log"
  log_path: "../log/codesand/"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "127.0.0.1"
  port: 8500
  tags:
    - "codesandsvr"