svr_config:
  name: "codesandsvr"
  host: "127.0.0.1"
  port: "8004"
  user_svr_name : "usersvr"
  question_svr_name : "questionsvr"
  implmethod: "remote"    # normal : 测试沙箱  remote : 远程沙箱  thirdpart: 第三方沙箱


redis:
  host: "127.0.0.1"
  password: "123456"
  db: 0
  port: 6379
  PoolSize: 10

mysql:
  host: "127.0.0.1"
  port: 3306
  database: oj
  username: root
  password: 123456

log:
  level: "debug"
  file_name: "codesand.log"
  log_path: "../log/codesand/"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "127.0.0.1"
  port: 8500
  tags:
    - "codesandsvr"

codesand:
  auth_header: "Auth"
  auth_key: "secretKey"